### ISSUE TITLE
change json format for social media to accept key/value pairs

### ISSUE THREAD

**Issue by fponticelli** [elm-resume/elm-resume#5]
From

```
socialMedia:
  - type: github
    value: janedoe80
  - type: twitter
    value: janedoe80
```

to

```
socialMedia:
  github: janedoe80
  twitter: janedoe80
```
